### ISSUE TITLE
Update to JBoss Fuse 6.2

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/jdg-fuse-demos#4]
Update to latest product.

**Comment by tqvarnst** [comment]
I've updated the products version and committed it into the dev branch, but there is a issue with karat dependencies. Christina is helping me looking into it.

**Comment by weimeilin79** [comment]
1. The init.sh has overwrite the entire repository, please avoid overwrite the agent properties file. Instead, I place the change in maven properties of the profile. 
2. The camel-core dependency is missing in the feature setting.
3. Feature.xml is out of date, so fixed it with new karaf namespace 
4. The release repository for Fuse is incorrect in pom.xml, fixed. 
5. Update JDK version to 1.8

Looks fine and worked fine in my laptop, Thomas, can you please confirm it in your laptop and if everything is fine, merge it to master?

**Comment by tqvarnst** [comment]
Resolved. Now based on JDG 6.5.0 (available on http://www.jboss.org/products/datagrid/download/) and updated to use remote listener for the remote-camel-consumer instead of polling.
